export const DRIVERS_POOL = {
    economico: [
        {
            id: 1,
            name: 'Juan Pérez',
            vehicleModel: 'Kia Picanto',
            licensePlate: 'JVR-101',
            rating: 4.8,
        },
        {
            id: 2,
            name: 'María López',
            vehicleModel: 'Chevrolet Spark',
            licensePlate: 'JVR-202',
            rating: 4.7,
        },
        {
            id: 3,
            name: 'Carlos Ruiz',
            vehicleModel: 'Hyundai i10',
            licensePlate: 'JVR-303',
            rating: 4.9,
        },
        {
            id: 4,
            name: 'Ana Gómez',
            vehicleModel: 'Renault Kwid',
            licensePlate: 'JVR-404',
            rating: 4.6,
        },
        {
            id: 5,
            name: 'Luis Torres',
            vehicleModel: 'Nissan March',
            licensePlate: 'JVR-505',
            rating: 4.8,
        },
    ],
    xl: [
        {
            id: 6,
            name: 'Pedro Méndez',
            vehicleModel: 'Toyota Fortuner',
            licensePlate: 'XL-606',
            rating: 4.9,
        },
        {
            id: 7,
            name: 'Elena Castro',
            vehicleModel: 'Chevrolet Tahoe',
            licensePlate: 'XL-707',
            rating: 4.9,
        },
        {
            id: 8,
            name: 'Jorge Silva',
            vehicleModel: 'Ford Expedition',
            licensePlate: 'XL-808',
            rating: 5.0,
        },
        {
            id: 9,
            name: 'Sofía Ríos',
            vehicleModel: 'Toyota Prado',
            licensePlate: 'XL-909',
            rating: 4.8,
        },
        {
            id: 10,
            name: 'Andrés Vaca',
            vehicleModel: 'Mitsubishi Montero',
            licensePlate: 'XL-010',
            rating: 4.9,
        },
    ],
    premium: [
        {
            id: 11,
            name: 'Valentina Daza',
            vehicleModel: 'Mercedes Benz C200',
            licensePlate: 'PRM-111',
            rating: 5.0,
        },
        {
            id: 12,
            name: 'Ricardo Arjona',
            vehicleModel: 'BMW Serie 3',
            licensePlate: 'PRM-222',
            rating: 5.0,
        },
        {
            id: 13,
            name: 'Camila Osorio',
            vehicleModel: 'Audi A4',
            licensePlate: 'PRM-333',
            rating: 4.9,
        },
        {
            id: 14,
            name: 'Felipe Neri',
            vehicleModel: 'Volvo S60',
            licensePlate: 'PRM-444',
            rating: 5.0,
        },
        {
            id: 15,
            name: 'Daniela Paz',
            vehicleModel: 'Tesla Model 3',
            licensePlate: 'PRM-555',
            rating: 5.0,
        },
    ],
};
